[package]
name = "prismatik-calendar"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
description = "PRISMATIK prismatik-calendar crate."

[dependencies]
prismatik-determinism.workspace = true
serde.workspace = true
time.workspace = true
thiserror.workspace = true
