apiVersion: v1
kind: Service
metadata:
  name: prismatik-api
  namespace: prismatik
  labels:
    app.kubernetes.io/name: prismatik-api
    app.kubernetes.io/part-of: prismatik
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: prismatik-api
  ports:
    - name: http
      port: 80
      targetPort: http
