[package]
name = "prismatik-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
description = "PRISMATIK prismatik-cli crate."

[dependencies]
prismatik-manifest.workspace = true
prismatik-application.workspace = true
prismatik-determinism.workspace = true
serde.workspace = true
serde_json.workspace = true
time.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true
