[package]
name = "prismatik-security"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
description = "PRISMATIK prismatik-security crate."

[dependencies]
thiserror.workspace = true
serde.workspace = true
prismatik-determinism.workspace = true
