[package]
name = "prismatik-features"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
description = "PRISMATIK prismatik-features crate."

[dependencies]
prismatik-domain.workspace = true
prismatik-market-data.workspace = true
