[package]
name = "prismatik-backtest"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
description = "PRISMATIK prismatik-backtest crate."

[dependencies]
prismatik-strategy.workspace = true
prismatik-calendar.workspace = true
prismatik-features.workspace = true
serde.workspace = true
thiserror.workspace = true
