[package]
name = "prismatik-domain"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
description = "PRISMATIK prismatik-domain crate."

[dependencies]
prismatik-determinism.workspace = true
prismatik-identity.workspace = true
serde.workspace = true
