[package]
name = "prismatik-market-data"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
description = "PRISMATIK prismatik-market-data crate."

[dependencies]
serde_json.workspace = true
prismatik-identity.workspace = true
prismatik-domain.workspace = true
prismatik-determinism.workspace = true
async-trait.workspace = true
serde.workspace = true
thiserror.workspace = true
time.workspace = true
blake3.workspace = true

[dev-dependencies]
tokio.workspace = true
