[package]
name = "prismatik-events"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
description = "PRISMATIK prismatik-events crate."

[dependencies]
thiserror.workspace = true
serde.workspace = true
prismatik-domain.workspace = true
prismatik-market-data.workspace = true
time.workspace = true

[dev-dependencies]
serde_json.workspace = true
